### PR TITLE
Add FMF test metadata and scripts

### PR DESCRIPTION
**Pull request by martinpitt**
- [x] PackageKit fixes: https://github.com/cockpit-project/cockpit/pull/15502

### CODE REVIEW

**Comment by martinpitt** [comment]
This [built fine in COPR](https://copr-be.cloud.fedoraproject.org/results/%40cockpit/ci-builds/fedora-33-x86_64/02056828-cockpit/) and I manually submitted it as a [testing farm request](https://api.dev.testing-farm.io/v0.1/requests/2401339c-a92b-4814-87fd-b6a6e622661a), but that immediately went into state "error" without much explanation. I *think* I followed the [API reasonably correctly](https://testing-farm.gitlab.io/api/#operation/requestsPost).

[pipeline.log with info](http://artifacts.dev.testing-farm.io/2401339c-a92b-4814-87fd-b6a6e622661a/pipeline.log)

That is not a good error message, see https://gitlab.com/testing-farm/general/-/issues/17

The problem is that there is no plan, I'll need to copy [all.fmf from e.g. podman](https://github.com/cockpit-project/cockpit-podman/blob/master/plans/all.fmf). Local tmt is happy with that, but TF not -- see [this issue](https://gitlab.com/testing-farm/general/-/issues/16).

**Comment by martinpitt** [comment]
Some progress -- one [failed](http://artifacts.dev.testing-farm.io/7189e922-0c33-41ab-9377-7b72d3659c27/) and one [success](http://artifacts.dev.testing-farm.io/dad5bf9a-f8ed-4376-8d3c-95611288b841/). `testServer` seems to have a hard time succeeding on that infra.

**Comment by martinpitt** [comment]
The [first packit run failed](https://prod.packit.dev/srpm-build/16090/logs) with a weird error message. Apparently related to https://github.com/packit/packit-service/issues/1017 .  Let's see if it is due to a timeout, I restart packit now, then the tarball should be available immediately.

**Comment by martinpitt** [comment]
Nice, that worked. https://github.com/packit/packit-service/issues/1017 is not too hard to work around, we would just need to send a `/packit build` comment from the end of the build-dist workflow. Hopefully this will get fixed soon, also.

My remaining investigation is how to trim the dist git
```
git clone https://github.com/martinpitt/cockpit-dist
cd cockpit-dist/
du -hsc .git/ *.tar
```

As expected, .git store and checkout coincide:
```
33M	.git/
8.3M	39816bb67587baeec45bd48001d53235be0f304f.tar
8.3M	59e812bd783da37b73268248db64bae6fc1f2414.tar
8.3M	72ca995616e15e0ad5c71d295879a863e607022d.tar
8.3M	f10c96d21254a63c19b37145ba8f5f86e5e2b60e.tar
66M	total
```

As a first measure, I think the build-dist workflow ought to immediately remove obsolete images each time, then it's less force-pushing, and we just need history pruning. There is a *lot* of non-working advice on the internet, but [this recipe](https://blog.ostermiller.org/removing-and-purging-files-from-git-history/) actually works:

```sh
git filter-branch --tag-name-filter cat --index-filter 'git rm -r --cached --ignore-unmatch 72ca995616e15e0ad5c71d295879a863e607022d.tar' --prune-empty -f -- --all
rm -r .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now
```

Et voilà, the oldest commit/file is gone, and the .git dir actually became smaller:
```
$ du -hsc .git *.tar
25M	.git
8.3M	39816bb67587baeec45bd48001d53235be0f304f.tar
8.3M	59e812bd783da37b73268248db64bae6fc1f2414.tar
8.3M	f10c96d21254a63c19b37145ba8f5f86e5e2b60e.tar
50M	total

$ git shortlog
Cockpit Project (3):
      Build for f10c96d21254a63c19b37145ba8f5f86e5e2b60e
      Build for 39816bb67587baeec45bd48001d53235be0f304f
      Build for 59e812bd783da37b73268248db64bae6fc1f2414
```

**Comment by martinpitt** [comment]
@TomasTomecek, @thrix: This somehow regressed. This morning I still got a (placeholder) pager for running tests, and a nicely formatted page for finished tests. Now the f33 one finished, but http://artifacts.dev.testing-farm.io/e98ea6bf-e2bc-4b7b-9e71-ec1ab50481b9 is still a 404, even though both the GitHub status and https://api.dev.testing-farm.io/v0.1/requests/e98ea6bf-e2bc-4b7b-9e71-ec1ab50481b9 say that it's done.

**Comment by thrix** [comment]
@martinpitt not regressed, but it is a new issue. Our workers started to have some weird DNS issues which caused that archiving of test artifacts faile. We run on Fedora 33, which introduced `systemd-resolved`, so we are investigating ....

**Comment by thrix** [comment]
I will restart once the outage is over, all I can do now :/

**Comment by martinpitt** [comment]
Thanks Miro! No worries, the test run itself is not precious. Good to hear that it's known and worked on!

Am 9. März 2021 20:01:52 MEZ schrieb Miroslav Vadkerti <notifications@github.com>:
>I will restart once the outage is over, all I can do now :/

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by martinpitt** [comment]
publish-dist landed, so now running against the "real" origin master code.

**Comment by martinpitt** [comment]
I fixed [this flake](http://artifacts.dev.testing-farm.io/4bdfa576-601f-4d48-8520-e41b8a7ebde9/) in a separate commit, and now enabled the optional test (which shouldn't be that many for Fedora). Let's give them a spin.

**Comment by martinpitt** [comment]
This [TestUpdates.testBasic failure](http://artifacts.dev.testing-farm.io/a9838466-3bbd-4bae-b0df-e4a4b4a9761f/) ([screenshot](http://artifacts.dev.testing-farm.io/a9838466-3bbd-4bae-b0df-e4a4b4a9761f/work-allYyorSc/plans/all/discover/default/tests/TestUpdates-testBasic-fedora-33-localhost-22-FAIL.png)) is a nuisance, I disabled it for now.

**Comment by martinpitt** [comment]
I think this is now ready for official submission.

**Pull request closed without merging**
